---
- hosts: network
  gather_facts: "no"
  become: "yes"
  roles:
    - network_common

- hosts: spines
  gather_facts: "no"
  become: "yes"
  roles:
  - spine

- hosts: leafs
  gather_facts: "no"
  become: "yes"
  roles:
  - leaf

- hosts: servers
  gather_facts: "no"
  become: "yes"
  roles:
    - server

- hosts: exits
  gather_facts: "no"
  become: "yes"
  roles:
    - exit

- hosts: internet
  gather_facts: "no"
  become: "yes"
  roles:
    - internet