---
- name: Copy FRR daemons file
  copy:
    src: daemons
    dest: /etc/frr/daemons
  notify: restart frr
  tags:
    - frr

- name: Copy interfaces configuration
  template:
    src: interfaces.j2
    dest: /etc/network/interfaces
  notify: reload networking
  tags:
    - interfaces

- name: Copy FRR configuration
  template:
    src: frr.j2
    dest: /etc/frr/frr.conf
  notify: reload frr
  tags:
    - frr
