---
- name: Add Cumulus Repo
  apt_repository:
    repo: deb https://apps3.cumulusnetworks.com/repos/deb CumulusLinux-3 netq-1.3
    state: present
  tags:
    - netq

- name: Upgrade NetQ
  apt:
    name: cumulus-netq
    state: latest
    update_cache: no
  tags:
    - netq

  # return code 0 means it's running
# return code 1 means it's not in the output of grep
# other return code is unknown
- name: Check if NTP is already in the vrf
  shell: "vrf task list | grep ntpd"
  register: ntp_vrf
  failed_when: ntp_vrf.rc >= 2
  tags:
    - netq

- name: Configure NTP in management VRF
  command: "{{item}}"
  with_items:
    - systemctl stop ntp.service
    - systemctl disable ntp.service
    - systemctl start ntp@mgmt
  when: ntp_vrf.rc != 0
  tags:
    - netq


  # - name: NetQ config
  #   shell: netq config show server
  #   register: netq_config 

  # - name: NetQ stats config
  #   shell: cat /etc/netq/netq.yml
  #   register: netq_stats_config

  # - name: Add netq server IP
  #   command: netq config add server 192.168.200.250 vrf mgmt
  #   when:
  #     - netq_config.stdout.find('192.168.200.250') == -1
  #     - netq_config.stdout.find('mgmt') == -1

  # - name: NetQ config
  #   shell: systemctl status netqd@mgmt
  #   register: netq_daemon_state 

  # - name: Restart NetQ Agent
  #   command: netq config restart agent
  #   when:
  #     - netq_daemon_state.stdout.find('active (running)') == -1

  # - name: Restart NetQ Agent
  #   command: netq config restart agent
  #   when:
  #     - netq_stats_config.stdout.find('stats') == -1
